version: '3.8'

services:
  mysql-server:
    image: mysql:latest
    container_name: mysql-server
    ports:
      - "3320:3306"
    environment:
      MYSQL_ROOT_PASSWORD: golang
      MYSQL_DATABASE: golang
      MYSQL_USER: golang
      MYSQL_PASSWORD: golang
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: