version: '3.8'

services:
  mysql-server:
    image: mysql:latest
    container_name: mysql-server
    ports:
      - "3320:3306"
    networks:
      - golang-network
    environment:
      MYSQL_ROOT_PASSWORD: golang
      MYSQL_DATABASE: golang
      MYSQL_USER: golang
      MYSQL_PASSWORD: golang
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:

networks:
  golang-network:
      name: golang-network
      driver: bridge
      driver_opts:
          com.docker.network.driver.mtu: 1450
      ipam:
          config:
              - subnet: 172.155.0.0/16